replaced datetime.datetime.now().strftime() with time.strftime() everywhere as datetime caused a weird bug on macOS: 'AttributeError: 'datetime.datetime' object has no attribute 'times'. Did you mean: 'time'?'